### ISSUE TITLE
No `day-render` event.

### ISSUE THREAD

**Issue by andrewspy** [sorin-davidoi/fullcalendar-calendar#12]
Missing `day-render` event, which allow backgrond of the day cells to use different color.

**Comment by sorin-davidoi** [comment]
There is [no event fired for `day-render`](https://github.com/sorin-davidoi/fullcalendar-calendar/blob/master/behaviors/full-calendar-behavior.html#L279) from the element because you cannot modify the cell this way (you need a synchronous callback for that). You can pass it like you normally would in FullCalendar;

```js
options = {
  dayRender: function (date, cell) {
    cell.css('background-color', 'red');
  },
  header: false,
  events: [
    { title: 'Discover fullcalendar-calendar', start: moment() },
    { title: 'Install fullcalendar-calendar', start: moment().add(2, 'day') },
    { title: 'Play around with fullcalendar-calendar', start: moment().add(4, 'days'), end: moment().add(5, 'days') },
    { title: 'Star fullcalendar-calendar on Github', start: moment().add(7, 'days'), end: moment().add(7, 'days').add(25, 'minutes') }
  ]
};
```

**Comment by andrewspy** [comment]
@sorin-davidoi Thanks for the explaination!
